"""Generate docs/data-dictionary.md from dictionary/*.yaml (the YAML stays the source of truth)."""
from .dictionary import STATUSES, load
from .paths import REPO

PRIVACY_TEXT = {
    "identity": "Identity - private store only, never in any build",
    "research": "Research - local research view only",
    "public_district": "Public, district-level summaries only",
    "public_village": "Public, village (cadastral) summaries",
}


def write_data_dictionary():
    d = load()
    lines = [
        "# RESOLVE data dictionary",
        "",
        "Generated by `python -m resolve docs` from `dictionary/*.yaml`. Do not edit by hand.",
        "",
        "## Value statuses",
        "",
        "| Status | Meaning |",
        "|---|---|",
        *[f"| `{code}` | {lab['en']} / {lab['ar']} |" for code, lab in STATUSES.items()],
        "",
        "## Instruments",
        "",
    ]
    for name, spec in d.instruments.items():
        lines += [f"### `{name}` - {spec['title']['en']}", "",
                  f"- Region: {spec['region']}", f"- Collected: {spec['collected']}", f"- Mode: {spec['mode']}",
                  f"- Source: `{spec['source_file']}`" + (f" (sheet `{spec['source_sheet']}`)" if spec.get("source_sheet") else ""),
                  f"- Note: {spec['source_note'].strip()}", ""]
    lines += ["## Fields", ""]
    for group, glabel in d.groups.items():
        fields = [f for f in d.fields if f.group == group]
        if not fields:
            continue
        lines += [f"### {glabel['en']} / {glabel['ar']}", "",
                  "| Code | Label | Type | Privacy | Vocabulary | Instruments | Applies if |", "|---|---|---|---|---|---|---|"]
        for f in fields:
            applies = f"`{f.applies_if['field']}` in {f.applies_if['in']}" if f.applies_if else ""
            lines.append(f"| `{f.code}` | {f.label['en']} / {f.label['ar']} | {f.type} | {PRIVACY_TEXT[f.privacy]} | "
                         f"{('`' + f.vocab + '`') if f.vocab else ''} | {', '.join(f.sources)} | {applies} |")
        lines.append("")
    lines += ["## Vocabularies", ""]
    for v in d.vocabularies.values():
        lines += [f"### `{v.name}` ({v.kind})", ""]
        if v.note:
            lines += [v.note.strip(), ""]
        lines += ["| Code | English | Arabic |", "|---|---|---|"]
        lines += [f"| `{c.code}` | {c.label['en']} | {c.label['ar']} |" for c in v.codes]
        lines.append("")
    path = REPO / "docs" / "data-dictionary.md"
    path.parent.mkdir(exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    return f"wrote {path.relative_to(REPO)}"
